package mx.itson.itsonoro.frames;

import com.google.gson.Gson;
import java.awt.Color;
import java.io.*;
import java.time.LocalDateTime;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import mx.itson.itsonoro.entidades.*;
import mx.itson.itsonoro.enumeradores.*;
import mx.itson.itsonoro.implementacion.*;

public class PaginaInicio extends javax.swing.JFrame {

    public static List<Usuario> listaUsuarios = new ArrayList<Usuario>();
    public static List<Curso> ListaCursos = new ArrayList<>();
    public static File datos = new File("C:\\Users\\sajos\\Documents\\NetBeansProjects\\Itsonoro.Presentacion\\BDD.txt");
    public static File datoscursos = new File("C:\\Users\\sajos\\Documents\\NetBeansProjects\\Itsonoro.Presentacion\\datoscurso.txt");
    public static Operaciones operacion = new Operaciones();
    Controlador controlador = new Controlador();
    Generador generador = new Generador();
    GUI interfazGrafica = new GUI();
    int index;
    boolean correoregistrado;

    public PaginaInicio() {
        initComponents();

        this.setLocationRelativeTo(null);
        PanelRegistro.setVisible(false);
        generador.predeterminados(listaUsuarios);
        frameProfesor.setLocationRelativeTo(null);
        frameAlumno.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameProfesor = new javax.swing.JFrame();
        pnlUsuario = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblCursoss = new javax.swing.JLabel();
        lblAsignacioness = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlAsignaciones = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstEntregas = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstAsignacionesB = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstCursosB = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblNombreT = new javax.swing.JLabel();
        lblComentarioT = new javax.swing.JLabel();
        lblValorT = new javax.swing.JLabel();
        lblFechaT = new javax.swing.JLabel();
        lblEntregaT = new javax.swing.JLabel();
        pnlCursos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstAlumnos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAsignaciones = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddTarea = new javax.swing.JButton();
        btnAddCurso = new javax.swing.JButton();
        txtNombreCurso = new javax.swing.JTextField();
        txtCodigoAcceso = new javax.swing.JTextField();
        txtInformacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreTarea = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtComentarioTarea = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtValorTarea = new javax.swing.JTextField();
        spnDate = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        frameAlumno = new javax.swing.JFrame();
        pnlUsuario1 = new javax.swing.JPanel();
        lblNombreUsuario1 = new javax.swing.JLabel();
        lblCursoss1 = new javax.swing.JLabel();
        lblAsignacioness1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        pnlCursos1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstAsignaciones1 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstCursos1 = new javax.swing.JList<>();
        jSeparator3 = new javax.swing.JSeparator();
        btnUpload = new javax.swing.JButton();
        pnlAsignaciones1 = new javax.swing.JPanel();
        bg1 = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();
        PanelPrincipal = new javax.swing.JPanel();
        PanelPresentacion = new javax.swing.JPanel();
        PanelBarraMenu = new javax.swing.JPanel();
        lblSaetiTress = new javax.swing.JLabel();
        lblRegistrar = new javax.swing.JLabel();
        LblSalir = new javax.swing.JLabel();
        lblmsj1 = new javax.swing.JLabel();
        lblmsj2 = new javax.swing.JLabel();
        lblImagenVerde = new javax.swing.JLabel();
        PanelInicioSesion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtInicioemail = new javax.swing.JTextField();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        pswContraInicio = new javax.swing.JPasswordField();
        BtnLogin = new javax.swing.JButton();
        lblInformacion = new javax.swing.JLabel();
        PanelRegistro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblInstitucion = new javax.swing.JLabel();
        txtInstitucion = new javax.swing.JTextField();
        lblTipoDeUsuario = new javax.swing.JLabel();
        CbxTipoDeUsuario = new javax.swing.JComboBox<>();
        BtnRegistrar = new javax.swing.JButton();
        txtFechaNacimiento = new javax.swing.JFormattedTextField();
        lblContraseña = new javax.swing.JLabel();
        lblConfirmarContraseña = new javax.swing.JLabel();
        pswcontraseña = new javax.swing.JPasswordField();
        pswconfirmarcontraseña = new javax.swing.JPasswordField();
        lblBack = new javax.swing.JLabel();

        frameProfesor.setMinimumSize(new java.awt.Dimension(720, 600));
        frameProfesor.setUndecorated(true);
        frameProfesor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre_del_Usuario");
        pnlUsuario.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 230, -1));

        lblCursoss.setForeground(new java.awt.Color(204, 204, 204));
        lblCursoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnCursos.png"))); // NOI18N
        lblCursoss.setText("Cursos");
        lblCursoss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCursoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursossMouseClicked(evt);
            }
        });
        pnlUsuario.add(lblCursoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        lblAsignacioness.setForeground(new java.awt.Color(204, 204, 204));
        lblAsignacioness.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnTareas.png"))); // NOI18N
        lblAsignacioness.setText("Asignaciones");
        lblAsignacioness.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsignacioness.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsignacionessMouseClicked(evt);
            }
        });
        pnlUsuario.add(lblAsignacioness, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnAyuda.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUsuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 0, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnLogout.png"))); // NOI18N
        jLabel4.setText("Log Out");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        pnlUsuario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlAsignaciones.setOpaque(false);
        pnlAsignaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Entregas");
        pnlAsignaciones.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Información de la Asignacion");
        pnlAsignaciones.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Asignaciones");
        pnlAsignaciones.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Cursos");
        pnlAsignaciones.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lstEntregas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstEntregas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntregasValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(lstEntregas);

        pnlAsignaciones.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 220, 180));

        lstAsignacionesB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAsignacionesB.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAsignacionesBValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstAsignacionesB);

        pnlAsignaciones.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 220, 180));

        lstCursosB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCursosB.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosBValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstCursosB);

        pnlAsignaciones.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 180));
        pnlAsignaciones.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 680, 20));

        jLabel7.setText("Nombre");
        pnlAsignaciones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jLabel19.setText("Comentario");
        pnlAsignaciones.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel20.setText("Valor");
        pnlAsignaciones.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel21.setText("Fecha de Creación");
        pnlAsignaciones.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel22.setText("Fecha de Entrega");
        pnlAsignaciones.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 480, -1, -1));

        lblNombreT.setText("-");
        pnlAsignaciones.add(lblNombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        lblComentarioT.setText("-");
        pnlAsignaciones.add(lblComentarioT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        lblValorT.setText("-");
        pnlAsignaciones.add(lblValorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        lblFechaT.setText("-");
        pnlAsignaciones.add(lblFechaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        lblEntregaT.setText("-");
        pnlAsignaciones.add(lblEntregaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        pnlUsuario.add(pnlAsignaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 720, 559));

        pnlCursos.setOpaque(false);
        pnlCursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstAlumnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(lstAlumnos);

        pnlCursos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 220, 180));

        lstAsignaciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(lstAsignaciones);

        pnlCursos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 180));

        lstCursos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCursos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursos);

        pnlCursos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 180));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Alumnos");
        pnlCursos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));
        pnlCursos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 680, 20));

        btnAddTarea.setText("Añadir");
        btnAddTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTareaActionPerformed(evt);
            }
        });
        pnlCursos.add(btnAddTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 80, -1));

        btnAddCurso.setText("Añadir");
        btnAddCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCursoActionPerformed(evt);
            }
        });
        pnlCursos.add(btnAddCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 80, -1));
        pnlCursos.add(txtNombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 220, -1));
        pnlCursos.add(txtCodigoAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 220, -1));
        pnlCursos.add(txtInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 220, -1));

        jLabel8.setText("Nombre");
        pnlCursos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel9.setText("Codigo de Acceso");
        pnlCursos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Cursos");
        pnlCursos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Asignaciones");
        pnlCursos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel10.setText("Información");
        pnlCursos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        pnlCursos.add(txtNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 200, -1));

        jLabel13.setText("Nombre");
        pnlCursos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel14.setText("Comentario");
        pnlCursos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));
        pnlCursos.add(txtComentarioTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 200, -1));

        jLabel15.setText("Valor");
        pnlCursos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));
        pnlCursos.add(txtValorTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 80, -1));

        spnDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1512498028455L), null, java.util.Calendar.DAY_OF_WEEK));
        pnlCursos.add(spnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 200, -1));

        jLabel5.setText("Fecha de Entrega");
        pnlCursos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        pnlUsuario.add(pnlCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 720, 559));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/bgUsuario.png"))); // NOI18N
        pnlUsuario.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        frameProfesor.getContentPane().add(pnlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 600));

        frameAlumno.setMinimumSize(new java.awt.Dimension(720, 600));
        frameAlumno.setUndecorated(true);

        pnlUsuario1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreUsuario1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNombreUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario1.setText("Nombre_del_Usuario");
        pnlUsuario1.add(lblNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 230, -1));

        lblCursoss1.setForeground(new java.awt.Color(204, 204, 204));
        lblCursoss1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnCursos.png"))); // NOI18N
        lblCursoss1.setText("Cursos");
        lblCursoss1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCursoss1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursoss1MouseClicked(evt);
            }
        });
        pnlUsuario1.add(lblCursoss1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        lblAsignacioness1.setForeground(new java.awt.Color(204, 204, 204));
        lblAsignacioness1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnTareas.png"))); // NOI18N
        lblAsignacioness1.setText("Asignaciones");
        lblAsignacioness1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAsignacioness1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAsignacioness1MouseClicked(evt);
            }
        });
        pnlUsuario1.add(lblAsignacioness1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnAyuda.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUsuario1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 0, -1, -1));

        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/btnLogout.png"))); // NOI18N
        jLabel25.setText("Log Out");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        pnlUsuario1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlCursos1.setOpaque(false);
        pnlCursos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Asignaciones");
        pnlCursos1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Cursos");
        pnlCursos1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lstAsignaciones1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAsignaciones1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstAsignaciones1ValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(lstAsignaciones1);

        pnlCursos1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 220, 180));

        lstCursos1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCursos1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursos1ValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(lstCursos1);

        pnlCursos1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 180));
        pnlCursos1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 248, 680, 10));

        btnUpload.setText("Entregar");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        pnlCursos1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        pnlUsuario1.add(pnlCursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 720, 559));

        pnlAsignaciones1.setOpaque(false);
        pnlAsignaciones1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlUsuario1.add(pnlAsignaciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 720, 559));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/bgUsuario.png"))); // NOI18N
        pnlUsuario1.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout frameAlumnoLayout = new javax.swing.GroupLayout(frameAlumno.getContentPane());
        frameAlumno.getContentPane().setLayout(frameAlumnoLayout);
        frameAlumnoLayout.setHorizontalGroup(
            frameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(frameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameAlumnoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        frameAlumnoLayout.setVerticalGroup(
            frameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(frameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frameAlumnoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(244, 249, 248));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        PanelPrincipal.setBackground(new java.awt.Color(251, 247, 245));
        PanelPrincipal.setMaximumSize(new java.awt.Dimension(1080, 360));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1080, 360));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1080, 360));
        PanelPrincipal.setLayout(null);

        PanelPresentacion.setBackground(new java.awt.Color(251, 247, 245));
        PanelPresentacion.setMaximumSize(new java.awt.Dimension(1080, 360));
        PanelPresentacion.setMinimumSize(new java.awt.Dimension(1080, 360));
        PanelPresentacion.setPreferredSize(new java.awt.Dimension(1080, 360));
        PanelPresentacion.setLayout(null);

        PanelBarraMenu.setBackground(new java.awt.Color(0, 204, 204));
        PanelBarraMenu.setMaximumSize(new java.awt.Dimension(1080, 60));
        PanelBarraMenu.setMinimumSize(new java.awt.Dimension(1080, 60));
        PanelBarraMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSaetiTress.setFont(new java.awt.Font("Microsoft Tai Le", 1, 28)); // NOI18N
        lblSaetiTress.setForeground(new java.awt.Color(255, 255, 255));
        lblSaetiTress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaetiTress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/Icono_saetitress.png"))); // NOI18N
        lblSaetiTress.setLabelFor(this);
        lblSaetiTress.setText(" SaetiTress");
        PanelBarraMenu.add(lblSaetiTress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 237, 38));

        lblRegistrar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 26)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistrar.setText("Registrar");
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        PanelBarraMenu.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 200, -1));

        LblSalir.setBackground(new java.awt.Color(251, 240, 247));
        LblSalir.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        LblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblSalir.setText("SALIR");
        LblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblSalirMouseClicked(evt);
            }
        });
        PanelBarraMenu.add(LblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 58, -1));

        PanelPresentacion.add(PanelBarraMenu);
        PanelBarraMenu.setBounds(0, 0, 1080, 60);

        lblmsj1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        lblmsj1.setForeground(new java.awt.Color(255, 255, 255));
        lblmsj1.setText("The perfect course");
        PanelPresentacion.add(lblmsj1);
        lblmsj1.setBounds(380, 130, 320, 60);

        lblmsj2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 36)); // NOI18N
        lblmsj2.setForeground(new java.awt.Color(255, 255, 255));
        lblmsj2.setText("Made possible by SaetiTress");
        PanelPresentacion.add(lblmsj2);
        lblmsj2.setBounds(300, 200, 490, 60);

        lblImagenVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/bgMenu.png"))); // NOI18N
        lblImagenVerde.setMaximumSize(new java.awt.Dimension(1080, 300));
        lblImagenVerde.setMinimumSize(new java.awt.Dimension(1080, 300));
        lblImagenVerde.setPreferredSize(new java.awt.Dimension(1080, 300));
        PanelPresentacion.add(lblImagenVerde);
        lblImagenVerde.setBounds(0, 60, 1080, 220);

        PanelPrincipal.add(PanelPresentacion);
        PanelPresentacion.setBounds(0, 0, 1080, 280);

        PanelInicioSesion.setBackground(new java.awt.Color(247, 243, 248));
        PanelInicioSesion.setMaximumSize(new java.awt.Dimension(1080, 370));
        PanelInicioSesion.setMinimumSize(new java.awt.Dimension(1080, 450));
        PanelInicioSesion.setOpaque(false);
        PanelInicioSesion.setPreferredSize(new java.awt.Dimension(1080, 450));
        PanelInicioSesion.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign in to SaetiTress");
        jLabel1.setMaximumSize(new java.awt.Dimension(260, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(260, 35));
        jLabel1.setPreferredSize(new java.awt.Dimension(260, 35));
        PanelInicioSesion.add(jLabel1);
        jLabel1.setBounds(380, 30, 310, 35);
        PanelInicioSesion.add(txtInicioemail);
        txtInicioemail.setBounds(410, 103, 260, 40);

        lblusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblusuario.setText("E-mail or Username");
        PanelInicioSesion.add(lblusuario);
        lblusuario.setBounds(410, 80, 260, 17);

        lblcontraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcontraseña.setText("Password");
        PanelInicioSesion.add(lblcontraseña);
        lblcontraseña.setBounds(410, 161, 260, 17);
        PanelInicioSesion.add(pswContraInicio);
        pswContraInicio.setBounds(410, 184, 260, 40);

        BtnLogin.setText("Log In");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        PanelInicioSesion.add(BtnLogin);
        BtnLogin.setBounds(410, 242, 260, 32);

        lblInformacion.setBackground(new java.awt.Color(238, 244, 238));
        lblInformacion.setText("     Saeti Tress ©  2017   Term & Uses");
        lblInformacion.setOpaque(true);
        PanelInicioSesion.add(lblInformacion);
        lblInformacion.setBounds(0, 415, 1080, 35);

        PanelPrincipal.add(PanelInicioSesion);
        PanelInicioSesion.setBounds(0, 280, 1080, 450);

        PanelRegistro.setBackground(new java.awt.Color(252, 240, 247));
        PanelRegistro.setMaximumSize(new java.awt.Dimension(1080, 450));
        PanelRegistro.setMinimumSize(new java.awt.Dimension(1080, 450));
        PanelRegistro.setPreferredSize(new java.awt.Dimension(1080, 450));

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Registro");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        lblNombre.setText("Nombre :");
        lblNombre.setMaximumSize(new java.awt.Dimension(200, 35));
        lblNombre.setMinimumSize(new java.awt.Dimension(200, 35));
        lblNombre.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtNombre.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        txtNombre.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtNombre.setMaximumSize(new java.awt.Dimension(200, 35));
        txtNombre.setMinimumSize(new java.awt.Dimension(200, 35));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 200, 35));

        lblEmail.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        lblEmail.setText("E-mail :");
        lblEmail.setMaximumSize(new java.awt.Dimension(200, 35));
        lblEmail.setMinimumSize(new java.awt.Dimension(200, 35));
        lblEmail.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 11, -1, -1));

        txtEmail.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(200, 35));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 54, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        lblTelefono.setText("Telefono :");
        lblTelefono.setMaximumSize(new java.awt.Dimension(200, 35));
        lblTelefono.setMinimumSize(new java.awt.Dimension(200, 35));
        lblTelefono.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 11, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        txtTelefono.setToolTipText("");
        txtTelefono.setMaximumSize(new java.awt.Dimension(200, 35));
        txtTelefono.setMinimumSize(new java.awt.Dimension(200, 35));
        txtTelefono.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 54, -1, -1));

        lblFechaNacimiento.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        lblFechaNacimiento.setText("Fecha De Nacimiento : (dd/MM/aaaa)");
        lblFechaNacimiento.setMaximumSize(new java.awt.Dimension(200, 35));
        lblFechaNacimiento.setMinimumSize(new java.awt.Dimension(200, 35));
        lblFechaNacimiento.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 13, -1, -1));

        lblInstitucion.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        lblInstitucion.setText("Institucion :");
        lblInstitucion.setMaximumSize(new java.awt.Dimension(200, 35));
        lblInstitucion.setMinimumSize(new java.awt.Dimension(200, 35));
        lblInstitucion.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 109, -1, -1));

        txtInstitucion.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        txtInstitucion.setMaximumSize(new java.awt.Dimension(200, 35));
        txtInstitucion.setMinimumSize(new java.awt.Dimension(200, 35));
        txtInstitucion.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(txtInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 150, -1, -1));

        lblTipoDeUsuario.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        lblTipoDeUsuario.setText("Tipo Usuario :");
        lblTipoDeUsuario.setMaximumSize(new java.awt.Dimension(200, 35));
        lblTipoDeUsuario.setMinimumSize(new java.awt.Dimension(200, 35));
        lblTipoDeUsuario.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblTipoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 109, -1, -1));

        CbxTipoDeUsuario.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        CbxTipoDeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "PROFESOR", "ALUMNO" }));
        CbxTipoDeUsuario.setMaximumSize(new java.awt.Dimension(200, 35));
        CbxTipoDeUsuario.setMinimumSize(new java.awt.Dimension(200, 35));
        CbxTipoDeUsuario.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(CbxTipoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 150, -1, -1));

        BtnRegistrar.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        BtnRegistrar.setText("REGISTRAR");
        BtnRegistrar.setMaximumSize(new java.awt.Dimension(200, 35));
        BtnRegistrar.setMinimumSize(new java.awt.Dimension(200, 35));
        BtnRegistrar.setPreferredSize(new java.awt.Dimension(200, 35));
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 332, -1, -1));

        txtFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtFechaNacimiento.setText("(dd/mm/aaaa)");
        txtFechaNacimiento.setMaximumSize(new java.awt.Dimension(200, 35));
        txtFechaNacimiento.setMinimumSize(new java.awt.Dimension(200, 35));
        txtFechaNacimiento.setPreferredSize(new java.awt.Dimension(200, 35));
        txtFechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaNacimientoFocusGained(evt);
            }
        });
        txtFechaNacimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaNacimientoMouseClicked(evt);
            }
        });
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 56, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Microsoft Tai Le", 0, 20)); // NOI18N
        lblContraseña.setText("Contraseña :");
        lblContraseña.setMaximumSize(new java.awt.Dimension(200, 35));
        lblContraseña.setMinimumSize(new java.awt.Dimension(200, 35));
        lblContraseña.setName(""); // NOI18N
        lblContraseña.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        lblConfirmarContraseña.setFont(new java.awt.Font("Microsoft Tai Le", 0, 18)); // NOI18N
        lblConfirmarContraseña.setText("Confirmar Contraseña :");
        lblConfirmarContraseña.setMaximumSize(new java.awt.Dimension(200, 35));
        lblConfirmarContraseña.setMinimumSize(new java.awt.Dimension(200, 35));
        lblConfirmarContraseña.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(lblConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 109, -1, -1));

        pswcontraseña.setMaximumSize(new java.awt.Dimension(200, 35));
        pswcontraseña.setMinimumSize(new java.awt.Dimension(200, 35));
        pswcontraseña.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(pswcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        pswconfirmarcontraseña.setToolTipText("");
        pswconfirmarcontraseña.setMaximumSize(new java.awt.Dimension(200, 35));
        pswconfirmarcontraseña.setMinimumSize(new java.awt.Dimension(200, 35));
        pswconfirmarcontraseña.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel1.add(pswconfirmarcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 150, -1, -1));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/itsonoro/imagenes/back.png"))); // NOI18N
        lblBack.setToolTipText("Regresar");
        lblBack.setMaximumSize(new java.awt.Dimension(200, 35));
        lblBack.setMinimumSize(new java.awt.Dimension(200, 35));
        lblBack.setPreferredSize(new java.awt.Dimension(200, 35));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(PanelRegistro);
        PanelRegistro.setBounds(0, 280, 1080, 440);

        getContentPane().add(PanelPrincipal);
        PanelPrincipal.setBounds(0, 0, 1080, 732);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        PanelRegistro.setVisible(true);
        PanelInicioSesion.setVisible(false);
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void LblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LblSalirMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked

        txtNombre.setText("");
        txtEmail.setText("");
        txtFechaNacimiento.setText("");
        txtInstitucion.setText("");
        txtTelefono.setText("");
        CbxTipoDeUsuario.setSelectedIndex(0);
        pswconfirmarcontraseña.setText("");
        pswcontraseña.setText("");

        PanelRegistro.setVisible(false);
        PanelInicioSesion.setVisible(true);

    }//GEN-LAST:event_lblBackMouseClicked

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        index = controlador.login(txtInicioemail.getText(), listaUsuarios, this, frameProfesor, pswContraInicio, frameAlumno);
        operacion.CargarTxt(datoscursos, ListaCursos);
        try {
            if(listaUsuarios.get(index).getTipoUsuario() == TipoUsuario.PROFESOR) {
                interfazGrafica.displayUsername(listaUsuarios.get(index), lblNombreUsuario);
                interfazGrafica.actualizarListaCursos(lstCursos, listaUsuarios.get(index));
                interfazGrafica.actualizarListaCursos(lstCursosB, listaUsuarios.get(index));
                pnlAsignaciones.setVisible(false);
                pnlCursos.setVisible(true);
            }else{
                if(listaUsuarios.get(index).getTipoUsuario() == TipoUsuario.ALUMNO){
                    interfazGrafica.displayUsername(listaUsuarios.get(index), lblNombreUsuario1);
                    interfazGrafica.actualizarListaCursos(lstCursos1, listaUsuarios.get(index));
                    pnlAsignaciones1.setVisible(false);
                    pnlCursos1.setVisible(true);
                }
            }
        } catch (Exception e) {
            ;
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        try {

            String email = txtEmail.getText();
            String telefono = txtTelefono.getText();
            Pattern pat = Pattern.compile("^[\\w-]+(\\.[\\w-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
            Matcher mat = pat.matcher(email);
            String contraseña = new String(pswcontraseña.getPassword());
            String confirmarcontraseña = new String(pswconfirmarcontraseña.getPassword());

            if (txtNombre.getText().equals("")
                    || txtEmail.getText().equals("")
                    || txtTelefono.getText().equals("")
                    || txtFechaNacimiento.getText().equals("")
                    || txtInstitucion.getText().equalsIgnoreCase("")
                    || CbxTipoDeUsuario.getSelectedItem().equals("SELECCIONAR")) {

                JOptionPane.showMessageDialog(null, "Favor De Llenar toda la informacion", "Error", JOptionPane.ERROR_MESSAGE);

                if (!mat.find()) {

                    JOptionPane.showMessageDialog(null, "Favor De Verificar Correo Electronico", "Error", JOptionPane.ERROR_MESSAGE);
                    lblEmail.setForeground(Color.red);
                    txtEmail.setText("");

                    if (!telefono.matches("[0-9]*")) {

                        JOptionPane.showMessageDialog(null, "Favor De Verificar Telefono", "Error", JOptionPane.ERROR_MESSAGE);
                        lblTelefono.setForeground(Color.red);
                        txtTelefono.setText("");

                        if (correoregistrado == true) {

                            JOptionPane.showMessageDialog(null, "Correo ya Registrado", "Error", JOptionPane.ERROR_MESSAGE);
                            lblEmail.setForeground(Color.red);

                            if (!confirmarcontraseña.equals(contraseña)) {

                                JOptionPane.showMessageDialog(null, "Las Contraseñas deben ser iguales", "Error", JOptionPane.ERROR_MESSAGE);
                                lblContraseña.setForeground(Color.red);
                                lblConfirmarContraseña.setForeground(Color.red);

                            }

                        }

                    }

                }

            } else {

                lblContraseña.setForeground(Color.black);
                lblConfirmarContraseña.setForeground(Color.black);
                lblEmail.setForeground(Color.black);
                lblTelefono.setForeground(Color.black);
                lblEmail.setText("E-mail :");

                Usuario usuario = new Usuario();
                usuario.setNombre(txtNombre.getText());
                usuario.setCorreoelectronico(txtEmail.getText());
                usuario.setCumpleaños(txtFechaNacimiento.getText());
                usuario.setInstitucion(txtInstitucion.getText());
                usuario.setTipoUsuario(TipoUsuario.valueOf(CbxTipoDeUsuario.getSelectedItem().toString()));
                usuario.setId(listaUsuarios.size());

                String contra = new String(pswcontraseña.getPassword());
                usuario.setContraseña(contra);

                operacion.Agregar(listaUsuarios, usuario);

                try {

                    operacion.ToJson(listaUsuarios, datos);

                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, "no sirve");

                }

                operacion.CargarTxt(datos, listaUsuarios);

                txtNombre.setText("");
                txtEmail.setText("");
                txtFechaNacimiento.setText("");
                txtInstitucion.setText("");
                txtTelefono.setText("");
                CbxTipoDeUsuario.setSelectedIndex(0);
                pswconfirmarcontraseña.setText("");
                pswcontraseña.setText("");

                JOptionPane.showMessageDialog(null, "El Usuario: " + usuario.getNombre() + " ha sido agregado", "Exito", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void txtFechaNacimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaNacimientoMouseClicked
        this.txtFechaNacimiento.setText("");
    }//GEN-LAST:event_txtFechaNacimientoMouseClicked

    private void txtFechaNacimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaNacimientoFocusGained
        this.txtFechaNacimiento.setText("");
    }//GEN-LAST:event_txtFechaNacimientoFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        String correov = txtEmail.getText();

        List<Usuario> Datos = new ArrayList<>();

        Datos = listaUsuarios.stream().filter(item -> item.getCorreoelectronico().equalsIgnoreCase(correov))
                .collect(Collectors.toList());

        boolean registrado = false;
        for (Usuario user : Datos) {
            if (user.getCorreoelectronico().equals(correov)) {
                registrado = true;
            } else {
                registrado = false;
            }
        }
        if (registrado == true) {
            lblEmail.setText("E-mail : (correo ya existe)");
            lblEmail.setForeground(Color.red);
            correoregistrado = true;
        } else if (registrado == false) {
            lblEmail.setText("E-mail :");
            lblEmail.setForeground(Color.black);
            correoregistrado = false;
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnAddCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCursoActionPerformed
        try {
            controlador.añadirCurso(listaUsuarios.get(index), txtNombreCurso, txtCodigoAcceso, txtInformacion);
            txtNombreCurso.setText("");
            txtCodigoAcceso.setText("");
            txtInformacion.setText("");
            interfazGrafica.actualizarListaCursos(lstCursos, listaUsuarios.get(index));
            interfazGrafica.actualizarListaCursos(lstCursosB, listaUsuarios.get(index));
        } catch (Exception e) {
            ;
        }

    }//GEN-LAST:event_btnAddCursoActionPerformed

    private void lstCursosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosValueChanged
        try {
            interfazGrafica.actualizarListas(lstAsignaciones, lstAlumnos, listaUsuarios.get(index).getCursos().get(lstCursos.getSelectedIndex()));
        } catch (Exception e) {
            ;
        }
    }//GEN-LAST:event_lstCursosValueChanged

    private void btnAddTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTareaActionPerformed
        try {
            controlador.añadirTarea(listaUsuarios.get(index).getCursos().get(lstCursos.getSelectedIndex()), txtNombreTarea, txtComentarioTarea, txtValorTarea, spnDate);
            interfazGrafica.actualizarListas(lstAsignaciones, lstAlumnos, listaUsuarios.get(index).getCursos().get(lstCursos.getSelectedIndex()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verificar que se haya seleccionado un curso.\nVerficar valor de los campos.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddTareaActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        frameProfesor.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void lblCursossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursossMouseClicked
        pnlCursos.setVisible(true);
        pnlAsignaciones.setVisible(false);
    }//GEN-LAST:event_lblCursossMouseClicked

    private void lblAsignacionessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsignacionessMouseClicked
        pnlAsignaciones.setVisible(true);
        pnlCursos.setVisible(false);
    }//GEN-LAST:event_lblAsignacionessMouseClicked

    private void lstCursosBValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosBValueChanged
        try {
            interfazGrafica.actualizarListas(lstAsignacionesB, lstAlumnos, listaUsuarios.get(index).getCursos().get(lstCursosB.getSelectedIndex()));
        } catch (Exception e) {
            ;
        }
    }//GEN-LAST:event_lstCursosBValueChanged

    private void lstAsignacionesBValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAsignacionesBValueChanged
        //System.out.println(listaUsuarios.get(index).getCursos().get(lstCursosB.getSelectedIndex()).getNombre());
        try {
            interfazGrafica.displayAsignacion(lblNombreT, lblComentarioT, lblValorT, lblFechaT, lblEntregaT, 
                    listaUsuarios.get(index).getCursos().get(lstCursosB.getSelectedIndex()).getAsignaciones().get(lstAsignacionesB.getSelectedIndex()));
            interfazGrafica.actualizarEntregas(lstEntregas, listaUsuarios.get(index).getCursos().get(lstCursosB.getSelectedIndex()).getAsignaciones().get(lstAsignacionesB.getSelectedIndex()));
        } catch (Exception e) {
            ;
        }
    }//GEN-LAST:event_lstAsignacionesBValueChanged

    private void lstEntregasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntregasValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstEntregasValueChanged

    private void lblCursoss1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursoss1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCursoss1MouseClicked

    private void lblAsignacioness1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAsignacioness1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAsignacioness1MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        frameAlumno.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void lstCursos1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursos1ValueChanged
        try {
            interfazGrafica.actualizarListas(lstAsignaciones1, lstAlumnos, listaUsuarios.get(index).getCursos().get(lstCursos1.getSelectedIndex()));
        } catch (Exception e) {
            ;
        }
    }//GEN-LAST:event_lstCursos1ValueChanged

    private void lstAsignaciones1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstAsignaciones1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lstAsignaciones1ValueChanged

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        fileChooser.setVisible(true);
    }//GEN-LAST:event_btnUploadActionPerformed

    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicio().setVisible(true);

                Usuario usuario;
                Gson gson = new Gson();

                try {

                    FileInputStream entrada;

                    entrada = new FileInputStream(datos);
                    String documento = "";
                    int ascci;

                    while ((ascci = entrada.read()) != -1) {

                        char caracter = (char) ascci;
                        documento += caracter;

                    }

                    if (documento.isEmpty()) {

                        JOptionPane.showMessageDialog(null, "El archivo esta en blanco");

                    } else {

                        String[] split = documento.split("_");

                        for (String json : split) {

                            usuario = gson.fromJson(json, Usuario.class);

                            listaUsuarios.add(usuario);

                        }

                    }

                } catch (Exception e) {
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JComboBox<String> CbxTipoDeUsuario;
    private javax.swing.JLabel LblSalir;
    private javax.swing.JPanel PanelBarraMenu;
    private javax.swing.JPanel PanelInicioSesion;
    private javax.swing.JPanel PanelPresentacion;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JButton btnAddCurso;
    private javax.swing.JButton btnAddTarea;
    private javax.swing.JButton btnUpload;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JFrame frameAlumno;
    private javax.swing.JFrame frameProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAsignacioness;
    private javax.swing.JLabel lblAsignacioness1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblComentarioT;
    private javax.swing.JLabel lblConfirmarContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCursoss;
    private javax.swing.JLabel lblCursoss1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEntregaT;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFechaT;
    private javax.swing.JLabel lblImagenVerde;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblInstitucion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreT;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNombreUsuario1;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblSaetiTress;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoDeUsuario;
    private javax.swing.JLabel lblValorT;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblmsj1;
    private javax.swing.JLabel lblmsj2;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JList<String> lstAlumnos;
    private javax.swing.JList<String> lstAsignaciones;
    private javax.swing.JList<String> lstAsignaciones1;
    private javax.swing.JList<String> lstAsignacionesB;
    private javax.swing.JList<String> lstCursos;
    private javax.swing.JList<String> lstCursos1;
    private javax.swing.JList<String> lstCursosB;
    private javax.swing.JList<String> lstEntregas;
    private javax.swing.JPanel pnlAsignaciones;
    private javax.swing.JPanel pnlAsignaciones1;
    private javax.swing.JPanel pnlCursos;
    private javax.swing.JPanel pnlCursos1;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JPanel pnlUsuario1;
    private javax.swing.JPasswordField pswContraInicio;
    private javax.swing.JPasswordField pswconfirmarcontraseña;
    private javax.swing.JPasswordField pswcontraseña;
    private javax.swing.JSpinner spnDate;
    private javax.swing.JTextField txtCodigoAcceso;
    private javax.swing.JTextField txtComentarioTarea;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFechaNacimiento;
    private javax.swing.JTextField txtInformacion;
    private javax.swing.JTextField txtInicioemail;
    private javax.swing.JTextField txtInstitucion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCurso;
    private javax.swing.JTextField txtNombreTarea;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtValorTarea;
    // End of variables declaration//GEN-END:variables
}
